baseURL = 'https://blog.atomage.cn'
languageCode = 'zh-cn'
title = 'ZhongsJie'
theme = 'ananke'

DefaultContentLanguage = "en"
enableRobotsTXT = true
hasCJKLanguage = true
summaryLength = 300

[params]

ananke_socials = [
  {name = "github", url = "https://github.com/ZhongsJie96"},
]




