baseURL: 'https://blogs.atomage.cn'  # 绑定的域名
languageCode: 'zh-cn' #en-us
title: Atomage's Blog
theme: 'ananke' # 主题
# 构建的目录定义
publishDir: "docs"

enableEmoji: true # 允许使用 Emoji 表情

enableInlineShortcodes: true
SectionPagesMenu: "main" 
Paginate: 8 # 首页每页显示的文章数
DefaultContentLanguage: "en"
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎
googleAnalytics: "G-HVT9CMYGB1" # googleAnalytics 谷歌统计
hasCJKLanguage: true # 自动检测是否包含 中文日文韩文
summaryLength: 300

params:
  ananke_socials:
  - name: "github"
    url: "https://github.com/ZhongsJie96"
  show_reading_time: true
  background_color_class: "bg-black"
  featured_image: "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number: 8

sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"
  priority: 0.5